### ISSUE TITLE
#02. WebpackOptionsValidationError

### ISSUE THREAD

**Issue by istiaqiut** [Remchi/reddice#11]
I tried to run npm run server after following #02. Project Setup: Render react component. and got following error-
/home/***/Desktop/reactcont/node_modules/webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/home/***/Desktop/reactcont/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/home/***/Desktop/reactcont/server/index.js:10:27)
    at Module._compile (module.js:541:32)
    at loader (/home/***/Desktop/reactcont/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/***/Desktop/reactcont/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at /home/***/Desktop/reactcont/node_modules/babel-cli/lib/_babel-node.js:155:24
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dborovsky** [comment]
If you are using webpack 2, extensions: `[' ', '.js']` can`t include empty elements in array. try [ '.js']. or downgrade to webpack v.1
