### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by cichy** [Remchi/reddice#12]
Tried to install and see errors
`> reddice@1.0.0 start /Users/admin/Git/reddice
> nodemon --watch server --exec babel-node -- server/index.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/admin/Git/reddice/server/**/*
[nodemon] starting `babel-node server/index.js`
Running on localhost:3000
Knex:Error Pool2 - Error: connect ECONNREFUSED 127.0.0.1:5432
Knex:Error Pool2 - Error: connect ECONNREFUSED 127.0.0.1:5432
webpack built 549ce7770cb1db2dac62 in 4571ms

Unhandled rejection Error: Pool is destroyed
    at Pool.acquire (/Users/admin/Git/reddice/node_modules/pool2/lib/pool.js:162:12)
    at /Users/admin/Git/reddice/node_modules/knex/src/client.js:212:29
    at Promise._execute (/Users/admin/Git/reddice/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:79:10)
    at Client.acquireConnection (/Users/admin/Git/reddice/node_modules/knex/src/client.js:208:23)
    at /Users/admin/Git/reddice/node_modules/knex/src/runner.js:188:49
    at Promise._execute (/Users/admin/Git/reddice/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:79:10)
    at /Users/admin/Git/reddice/node_modules/knex/src/runner.js:187:35
    at tryCatcher (/Users/admin/Git/reddice/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/admin/Git/reddice/node_modules/bluebird/js/release/method.js:39:29)
    at Runner.ensureConnection (/Users/admin/Git/reddice/node_modules/knex/src/runner.js:186:23)
    at Runner.run (/Users/admin/Git/reddice/node_modules/knex/src/runner.js:27:31)
    at QueryBuilder.Target.then (/Users/admin/Git/reddice/node_modules/knex/src/interface.js:22:45)

Unhandled rejection Error: Pool is destroyed
    at Pool.acquire (/Users/admin/Git/reddice/node_modules/pool2/lib/pool.js:162:12)
    at /Users/admin/Git/reddice/node_modules/knex/src/client.js:212:29
    at Promise._execute (/Users/admin/Git/reddice/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:79:10)
    at Client.acquireConnection (/Users/admin/Git/reddice/node_modules/knex/src/client.js:208:23)
    at /Users/admin/Git/reddice/node_modules/knex/src/runner.js:188:49
    at Promise._execute (/Users/admin/Git/reddice/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:79:10)
    at /Users/admin/Git/reddice/node_modules/knex/src/runner.js:187:35
    at tryCatcher (/Users/admin/Git/reddice/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/admin/Git/reddice/node_modules/bluebird/js/release/method.js:39:29)
    at Runner.ensureConnection (/Users/admin/Git/reddice/node_modules/knex/src/runner.js:186:23)
    at Runner.run (/Users/admin/Git/reddice/node_modules/knex/src/runner.js:27:31)
    at QueryBuilder.Target.then (/Users/admin/Git/reddice/node_modules/knex/src/interface.js:22:45)

Unhandled rejection Error: Pool is destroyed
    at Pool.acquire (/Users/admin/Git/reddice/node_modules/pool2/lib/pool.js:162:12)
    at /Users/admin/Git/reddice/node_modules/knex/src/client.js:212:29
    at Promise._execute (/Users/admin/Git/reddice/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:79:10)
    at Client.acquireConnection (/Users/admin/Git/reddice/node_modules/knex/src/client.js:208:23)
    at /Users/admin/Git/reddice/node_modules/knex/src/runner.js:188:49
    at Promise._execute (/Users/admin/Git/reddice/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/admin/Git/reddice/node_modules/bluebird/js/release/promise.js:79:10)
    at /Users/admin/Git/reddice/node_modules/knex/src/runner.js:187:35
    at tryCatcher (/Users/admin/Git/reddice/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/admin/Git/reddice/node_modules/bluebird/js/release/method.js:39:29)
    at Runner.ensureConnection (/Users/admin/Git/reddice/node_modules/knex/src/runner.js:186:23)
    at Runner.run (/Users/admin/Git/reddice/node_modules/knex/src/runner.js:27:31)
    at QueryBuilder.Target.then (/Users/admin/Git/reddice/node_modules/knex/src/interface.js:22:45)

`

**Comment by iqbalsafian** [comment]
it was coming from knex, i bet that you didn't have the postgres dbase created, didn't you?
